codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 90%
        threshold: 1%
        if_no_uploads: error
    patch:
      default:
        target: 80%
        threshold: 5%

comment:
  layout: "reach,diff,flags,tree,betaprofiling"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "example/**/*"
  - "**/*.g.dart"
  - "**/*.freezed.dart"
